Add pundit
jniewiel/industrial-auth-1 pull request #2
Opened 2024-07-17 21:50 UTC by jniewiel

2024-07-18 16:28 UTC, aborov approved these changes
That's a ton of work! Great job, Jan!

2024-07-18 16:28 UTC, aborov commented on app/controllers/application_controller.rb
> +  end
Nice job including Pundit on application level to go "secured by default"

2024-07-18 16:28 UTC, aborov commented on app/controllers/follow_requests_controller.rb
> +  before_action :authorize_follow_request, except: %i[ index new create ]
Great use of `before_action` to set restrictions for users to manipulate follow requests

2024-07-18 16:28 UTC, aborov commented on app/controllers/follow_requests_controller.rb
> +    authorize(@follow_request)
Great job calling `authorize` method on new follow requests as they don't yet exist as objects before the moment of creation

2024-07-18 16:28 UTC, aborov commented on app/controllers/users_controller.rb
> +  end
Awesome work defining all the actions for users to make the policy work

2024-07-18 16:28 UTC, aborov commented on app/policies/comment_policy.rb
> +  end
Great use of conditional statement to define which comments a user can see

2024-07-18 16:28 UTC, aborov commented on app/views/users/_user.html.erb
>          <% end %>
great job closing someone else's pending requests in view

2024-07-19 19:30 UTC, aizatibraimova commented on app/controllers/application_controller.rb
Your code is clean and easy to read.

2024-07-19 19:34 UTC, aizatibraimova commented on app/controllers/comments_controller.rb
Great job on ensuring that users only see comments they are authorized to view by adding `policy_scope(Comment)` in the index action.

2024-07-19 19:34 UTC, aizatibraimova approved these changes

2024-07-22 20:29 UTC, ajmompr requested changes
Almost! Take a closer look at your user policy

2024-07-22 20:29 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_authorized, unless: :devise_controller?
good job accounting devise

2024-07-22 20:29 UTC, ajmompr commented on app/controllers/comments_controller.rb
good; can be refactored to be more DRY! But this is OK!

2024-07-22 20:29 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
good!

2024-07-22 20:29 UTC, ajmompr commented on app/controllers/photos_controller.rb
good

2024-07-22 20:29 UTC, ajmompr commented on app/controllers/users_controller.rb
good

2024-07-22 20:29 UTC, ajmompr commented on app/policies/user_policy.rb
you are missing an additional policy called show_photos? That will account for edge cases/private accounts. Instead of calling .show? in your users#show page, you should be calling .show_photos?

2024-07-23 17:25 UTC, ajmompr requested changes
slight change needed to user policy

2024-07-23 17:25 UTC, ajmompr commented on app/views/users/show.html.erb
> +<% if policy(@user).show_photos? %>
good

2024-07-23 17:25 UTC, ajmompr commented on app/policies/user_policy.rb
> +    current_user == @user || !@user.private? || current_user.leaders.include?(@user)
shouldn't be @user. should just be user

2024-07-23 21:07 UTC, heratyian commented on app/policies/photo_policy.rb
> +      scope.all.select do |photo|
fwiw using a select do block here wont scale or work with pagination since we have to load all the objects into memory.

2024-07-23 21:08 UTC, heratyian commented on app/policies/user_policy.rb
> +  class Scope < Scope
👍

2024-07-24 13:53 UTC, ajmompr approved these changes

2024-07-24 16:15 UTC, merged